config/routes.rb
Rails.application.routes.draw do

  # Home, sales, informational pages
  #
  get "/about", to: "home#about", as: "about"
  get "/terms-of-use", to: "home#tos", as: "tos"
  get "/privacy-policy", to: "home#pp", as: "pp"

  # Allow user+email sign up, along with choice Oauth providers (ex: twitter, facebook)
  devise_for :users,
             :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :registrations => 'custom_devise/registrations', :sessions => 'custom_devise/sessions', :passwords => 'custom_devise/passwords' }

  # A user of a system may manage multiple accounts
  resources :users

  resources :face_match_results do
      resources :face_matches
  end

  get "/face_match_results/:id/processing" => 'face_match_results#processing', :as => 'face_match_result_processing'

  #
  # Dashboard
  #

  scope "/dashboards/:account_uuid", :as => 'dashboard' do
    resources :services
    resources :activity_stream
  end

  get "/dashboards/:account_uuid" => 'dashboards#index', :as => 'dashboards'

  get "/dashboards" => 'dashboards#base', :as => 'dashboard_init_path'
  #
  # Account bootstrapping screens
  #
  # @note: Authorization and omni auth intermediate steps to get a user fully onboard.
  # For instance: Twitter does not provide a user name, while facebook does
  # Additionally, you may want a quick 'configuration' step for a subdomain for the user
  # In the latter case, you will prompt for the field in setup_site
  match '/users/:id/setup' => 'users#setup', via: [:get, :patch], :as => :setup
  match '/users/:id/setup_site' => 'users#setup_site', via: [:get, :patch], :as => :setup_site
  
  #
  # Client API
  #
  # Provides restful api to all clients
  namespace :service do
    # Validator allows pre-sign up validation (ex: username in use)
    get '/v1/setup/validate' => 'setup_validator#validate', as: 'api_setup_sites_validate'
    # Simple newsletter subscription request (for those seeking to signup to Our Very Own Newsletter)
    post '/v1/newsletter_subscriptions' => 'api_newsletter_subscriptions#create', as: 'api_newsletter_subscriptions_create'
  end

  #
  # Housekeeping
  #

  # Verifies that the user has an account and is the manager of at least one account, then redirects to the appropriate site page
  # This is useful for handling Twitter/Facebook/Oauth logins where the email is not provided and we need an email or password
  get '/init', to: 'init#index', as: 'init'
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  # Route to home if no other routes match
  root to: 'home#index'
end

app/models/service.rb
require 'active_resource'
class Service < ActiveResource::Base
  self.site = Rails.configuration.api_megamatcher_connection[:url]
  self.prefix = '/manage/v1/accounts/:account_uuid/'

  #fortify :name, :specification, :service_uuid
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  layout 'dashboards'
  protect_from_forgery with: :null_session
  def index
    @account_uuid = current_or_guest_account.account_uuid
    @services = List.run!(account_uuid: current_or_guest_account.account_uuid)
  end

  def show
    @account_uuid = current_or_guest_account.account_uuid
    @service = GetService.run!(account_uuid: @account_uuid, service_uuid: params[:id])
  end

  def new
    @account_uuid = current_or_guest_account.account_uuid
    @service = Service.build(account_uuid: @account_uuid)
  end

  def edit
    @account_uuid = current_or_guest_account.account_uuid
    @service = GetService.run!(account_uuid: @account_uuid, service_uuid: params[:id])
  end

  def update
    @account_uuid = current_or_guest_account.account_uuid
    @service = Update.run!(account_uuid: @account_uuid,
                                  service_uuid: params[:id],
                                  specification: service_params[:specification],
                                  subdomain: service_params[:subdomain],
                                  name: service_params[:name])

    redirect_to dashboard_service_path(@account_uuid, @service.service_uuid)
  end

  def create
    @account_uuid = current_or_guest_account.account_uuid
    outcome = Create.run(account_uuid: @account_uuid, name: service_params[:name], specification: service_params[:specification])

    respond_to do |format|
      if outcome.valid?
        format.html { redirect_to dashboard_service_path(outcome.result.service_uuid, account_uuid: @account_uuid), notice: 'Service successfully created' }
        format.json { render json: outcome.result, status: :created }
      else
        format.html { render action: 'edit' }
        format.json { render json: outcome.errors.full_messages.to_sentence, status: :unprocessable_entity }
      end
    end

  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :specification, :subdomain)
  end
end

app/views/services/_form.html.slim
= form_tag dashboard_services_path(account_uuid: @account_uuid) do |f|

  - if @service.errors.any?
    div id="error_explanation"
      h2
        = pluralize(@service.errors.count, "error")
          | prohibited this service from being saved:
      ul
        - @service.errors.full_messages.each do |message|
          = message

  div
    = label_tag :service, :name
    br
    = text_field :service, :name, required: true


  div
    = label_tag :service, :specification
    br
    div id="service_specification_editor"

    = text_area :service, :specification, class: 'hide spec-editor'

  div.actions
    = submit_tag 'Create Service', class: 'btn btn-success'

app/views/services/_form_edit.html.slim
= form_tag dashboard_service_path(id: @service.service_uuid, account_uuid: @account_uuid), :method => 'put' do |f|

  - if @service.errors.any?
    div id="error_explanation"
      h2
        = pluralize(@service.errors.count, "error")
          | prohibited this service from being saved:
      ul
        - @service.errors.full_messages.each do |message|
          = message

  div

    = text_field :service, :name, required: true, class: 'service-name-edit'

  div
    p
      | https://
      = text_field :service, :subdomain, required: true, class: 'service-subdomain-edit'
      | .api.symmetry.io/v1
      =>
      a href="#"
        | view
        =>
        i.fa.fa-caret-down
  div
    = text_area :service, :specification, required: true, class: 'service-name-edit', :rows => 20, :cols => 80

  h2
    | Object strucur
  div.hide
    br
    div id="service_specification_editor"

    = text_area :service, :specification, class: 'hide hidden'

  h1
    | Models
  div.actions
    = submit_tag 'Update Service', class: 'btn btn-success'

app/views/services/edit.html.slim
= render 'form_edit'

= link_to 'Show', dashboard_service_path(@service.service_uuid, account_uuid: @account_uuid)
= link_to 'Back', dashboard_services_path(account_uuid: @account_uuid)

app/views/services/index.html.slim
h1
  | Services

= link_to 'New service', new_dashboard_service_path(account_uuid: @account_uuid)


- @services.each do |service|
  h2
    = service.name
    =>
    | Service
    =>
    | (
    = link_to 'View', dashboard_service_path(service.service_uuid, account_uuid: @account_uuid)
    | )

app/views/services/new.html.erb
<h1>New Api</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_services_path %>

app/views/services/show.html.slim
p id="notice"
  = notice

p
  strong
    | Name:
  = @service.name

p
  strong
    | Subdomain:
  = @service.subdomain

p
  strong
    | Specification:
  = @service.specification


= link_to 'Edit', edit_dashboard_service_path(@service.service_uuid, account_uuid: @account_uuid )
| |

= link_to 'Back', dashboard_services_path